# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Gabriela Cavalcante
tagline:          
url:              http://www.i-am-gabi.github.io
shorturl:         i-am-gabi.github.io

author:
  name:           'Gabriela Cavalcante'
  url:            https://twitter.com/joshualande

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/joshualande/joshualande.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Posts: '/archive/'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
