excerpt_separator: ""
pygments: true
markdown: kramdown
title: Gabi
tagline: code to back home
description: code with melancholic track
paginate: 5
author:
  reidark:
    name: reidark
    url: http://i-am-gabi.github.io
    description: Tentando ser útil
