excerpt_separator: ""
pygments: true
markdown: kramdown
title: Gabi
tagline: e
description: porque programar sempre é a melhor opção
paginate: 5
author:
  reidark:
    name: reidark
    url: http://i-am-gabi.github.io
    description: Tentando ser útil
