excerpt_separator: ""
pygments: true
markdown: kramdown
title: I++
tagline: porque programar sempre é a melhor opção
description: programadora e entusiasta de software livre
paginate: 5
author:
  gabriela:
    name: Gabriela
    url: http://i-am-gabi.github.io
    description: Tentando ser útil
