excerpt_separator: ""
pygments: true
markdown: kramdown
title: I-am-Gabi
tagline: 
description: Programadora e entusiasta de software livre
paginate: 5
author:
  gabriela:
    name: Gabriela
    url: http://i-am-gabi.github.io
    description: Tentando ser útil
